#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <gcrypt.h>

// Generate spar = (G, g, q) from kappa → GENERATED BY CIPHER SUITE
/*
    int SETUP (int kappa) {
        
        return 0;
    }
*/

// Generate pk_c and sk_c from kappa → GENERATED BY CIPHER SUITE
/*
    int CLIENT_REGISTER (int kappa) {
        
        return 0;
    }
*/

int SERVER_SIGNVERIFY (int Y, int pk_s, int sk_c) {
    
    return 0;
}

int CLIENT_PROOFVERIFY (int Y, int sigma, int pk_s, int sk_c) {
    
    return 0;
}